CREATE DATABASE cf_sql CHARACTER SET ‘utf8’;

USE cf_sql;
CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    mail VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(80) NOT NULL,
    pseudo VARCHAR(20) NOT NULL UNIQUE,
    adress VARCHAR(255) NULL,
    cp INT(6) UNSIGNED NULL,
    city VARCHAR(60) NULL,
    country VARCHAR(50) NULL,
    phone_numbers VARCHAR(15) NULL,
    house_numbers VARCHAR(15) NULL,
    signin_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARACTER SET 'utf8'
ENGINE = INNODB;

CREATE TABLE services(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    id_user INT UNSIGNED NOT NULL,
    name VARCHAR(50) NOT NULL,
    description TEXT NOT NULL,
    address VARCHAR(255) NOT NULL,
    cp INT(6) UNSIGNED NOT NULL,
    city VARCHAR(50) NOT NULL,
    country VARCHAR(60) NOT NULL,
    date_hour DATETIME DEFAULT CURRENT_TIMESTAMP,
    more_info TEXT,
    PRIMARY KEY(id)
)
CHARACTER SET 'utf8'
ENGINE=INNODB;

