CREATE TABLE services_users(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
id_service INT UNSIGNED NOT NULL,
id_user INT UNSIGNED NOT NULL,
sign_date_hour DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
)
ENGINE = INNODB;
